# -*- coding: utf-8 -*-
"""AIFA PROJECT"""

#Automatically generated by Colab.

#Original file is located at
    #https://colab.research.google.com/drive/14yotJvqOHeEp6npqMIWGvYEwH2As7MNQ

"""### WITH ALPHA BETA"""

import numpy as np
import math
import time
import networkx as nx
import matplotlib.pyplot as plt

# GRAPH SETUP
G = nx.DiGraph()
node_counter = 0
eval_count = 0

def new_node(label, ntype):
    global node_counter
    node_id = f"N{node_counter}"
    G.add_node(node_id, label=label, ntype=ntype)
    node_counter += 1
    return node_id


# MODEL
def simulate(R, Q, T, F):
    purity = (
        0.82
        + 0.15 * math.tanh(R - 2)
        - 0.5 * abs(F - 0.5)
        - 0.01 * (T - 78)**2
    )
    energy = Q + 80 * R + 0.5 * abs(T - 78)
    return purity, energy


def utility(purity, energy):
    penalty = 0
    if purity < 0.88:
        penalty = -200 * (0.88 - purity)
    return 120 * purity - 0.07 * energy + penalty


def update_feed(prev_F, disturbance):
    return 0.6 * prev_F + 0.4 * disturbance


# RANGES
reflux_values = np.linspace(1, 4, 3)
heat_values   = np.linspace(300, 700, 3)
temp_values   = np.linspace(70, 90, 3)
feed_values   = np.linspace(0.1, 1.0, 3)


# MINIMAX WITH CORRECT PRUNING
def minimax(depth, is_max, state, alpha, beta, parent):

    global eval_count
    R, Q, T, F = state

    # LEAF
    if depth == 0:
        eval_count += 1

        purity, energy = simulate(R, Q, T, F)
        u = utility(purity, energy)

        leaf = new_node(f"{u:.1f}", "LEAF")
        G.add_edge(parent, leaf)

        return u, [state], [leaf]

    # MAX
    if is_max:
        node = new_node("MAX", "MAX")
        G.add_edge(parent, node)

        best = float('-inf')
        best_states = []
        best_nodes = []

        prune_flag = False

        for r in reflux_values:
            if prune_flag: break
            for q in heat_values:
                if prune_flag: break
                for t in temp_values:

                    new_state = (r, q, t, F)

                    val, states, nodes = minimax(
                        depth-1, False,
                        new_state,
                        alpha, beta, node
                    )

                    if val > best:
                        best = val
                        best_states = [state] + states
                        best_nodes = [node] + nodes

                    alpha = max(alpha, best)

                    if beta <= alpha:
                        prune = new_node("PRUNED", "PRUNED")
                        G.add_edge(node, prune)
                        prune_flag = True
                        break

        return best, best_states, best_nodes

    # MIN
    else:
        node = new_node("MIN", "MIN")
        G.add_edge(parent, node)

        worst = float('inf')
        worst_states = []
        worst_nodes = []

        for d in feed_values:
            new_F = update_feed(F, d)
            new_state = (R, Q, T, new_F)

            val, states, nodes = minimax(
                depth-1, True,
                new_state,
                alpha, beta, node
            )

            if val < worst:
                worst = val
                worst_states = [state] + states
                worst_nodes = [node] + nodes

            beta = min(beta, worst)

            if beta <= alpha:
                prune = new_node("PRUNED", "PRUNED")
                G.add_edge(node, prune)
                break

        return worst, worst_states, worst_nodes


# TREE LAYOUT
def hierarchy_pos(G, root):
    pos = {}
    levels = {}

    def dfs(node, depth=0):
        if depth not in levels:
            levels[depth] = []
        levels[depth].append(node)
        for child in G.successors(node):
            dfs(child, depth+1)

    dfs(root)

    for depth, nodes in levels.items():
        width = len(nodes)
        for i, node in enumerate(nodes):
            pos[node] = (i - width/2, -depth)

    return pos


# DRAWING TREE

def draw_tree(G, root, path_edges):

    pos = hierarchy_pos(G, root)
    labels = nx.get_node_attributes(G, 'label')
    types = nx.get_node_attributes(G, 'ntype')

    colors = []
    for n in G.nodes():
        t = types[n]
        if t == "MAX":
            colors.append("skyblue")
        elif t == "MIN":
            colors.append("lightcoral")
        elif t == "LEAF":
            colors.append("lightgreen")
        elif t == "PRUNED":
            colors.append("grey")
        else:
            colors.append("black")

    plt.figure(figsize=(16,10))

    nx.draw(G, pos, node_color=colors, node_size=2000, with_labels=False)
    nx.draw_networkx_labels(G, pos, labels, font_size=7)

    nx.draw_networkx_edges(
        G, pos,
        edgelist=path_edges,
        width=3,
        edge_color="blue"
    )

    plt.title("Minimax Tree with Correct Alpha-Beta Pruning")
    plt.axis('off')
    plt.show()



root = new_node("ROOT", "ROOT")
initial_state = (2.5, 500, 78, 0.5)

start = time.time()

value, states, nodes = minimax(
    4, True, initial_state,
    float('-inf'), float('inf'),
    root
)

runtime = time.time() - start

path_edges = list(zip(nodes, nodes[1:]))

# OUTPUT

print("\n=OPTIMAL STATE TRANSITIONS=\n")
for i, s in enumerate(states):
    print(f"Step {i}: R={s[0]:.2f}, Q={s[1]:.1f}, T={s[2]:.1f}, F={s[3]:.2f}")

print("\n =FINAL RESULT=")
print(f"Final Utility = {value:.2f}")
print(f"Nodes Evaluated = {eval_count}")
print(f"Runtime = {runtime:.4f} sec")

draw_tree(G, root, path_edges)

"""### WITHOUT ALPHA BETA PRUNING"""

import numpy as np
import math
import time

eval_count = 0   

def simulate(R, Q, T, F):
    purity = (
        0.82
        + 0.15 * math.tanh(R - 2)
        - 0.5 * abs(F - 0.5)
        - 0.01 * (T - 78)**2
    )
    energy = Q + 80 * R + 0.5 * abs(T - 78)
    return purity, energy


def utility(purity, energy):
    penalty = 0
    if purity < 0.88:
        penalty = -200 * (0.88 - purity)
    return 120 * purity - 0.07 * energy + penalty


def update_feed(prev_F, disturbance):
    return 0.6 * prev_F + 0.4 * disturbance


reflux_values = np.linspace(1, 4, 3)
heat_values   = np.linspace(300, 700, 3)
temp_values   = np.linspace(70, 90, 3)
feed_values   = np.linspace(0.1, 1.0, 3)


def minimax(depth, is_max, state):

    global eval_count   
    R, Q, T, F = state

    if depth == 0:
        eval_count += 1   

        purity, energy = simulate(R, Q, T, F)
        return utility(purity, energy), [state]

    if is_max:
        best = float('-inf')
        best_path = []

        for r in reflux_values:
            for q in heat_values:
                for t in temp_values:

                    val, path = minimax(
                        depth-1, False,
                        (r, q, t, F)
                    )

                    if val > best:
                        best = val
                        best_path = [state] + path

        return best, best_path

    else:
        worst = float('inf')
        worst_path = []

        for d in feed_values:
            new_F = update_feed(F, d)

            val, path = minimax(
                depth-1, True,
                (R, Q, T, new_F)
            )

            if val < worst:
                worst = val
                worst_path = [state] + path

        return worst, worst_path


# RUN
initial_state = (2.5, 500, 78, 0.5)

start = time.time()

value, states = minimax(4, True, initial_state)

runtime = time.time() - start

print("\n=OUTPUT (NO PRUNING)=")
for i, s in enumerate(states):
    print(f"Step {i}: R={s[0]:.2f}, Q={s[1]:.1f}, T={s[2]:.1f}, F={s[3]:.2f}")

print("\nFinal Utility =", round(value,2))
print("Nodes Evaluated =", eval_count)   
print("Runtime =", round(runtime,4), "sec")

"""### Comparision"""

import time
import tracemalloc
import math

#Global Counters
eval_count_std = 0
eval_count_ab = 0

# 1. STANDARD MINIMAX
def minimax_standard(depth, is_max, state):
    global eval_count_std
    R, Q, T, F = state

    if depth == 0:
        eval_count_std += 1
        purity, energy = simulate(R, Q, T, F)
        return utility(purity, energy), [state]

    if is_max:
        best = float('-inf')
        best_path = []
        for r in reflux_values:
            for q in heat_values:
                for t in temp_values:
                    val, path = minimax_standard(depth-1, False, (r, q, t, F))
                    if val > best:
                        best = val
                        best_path = [state] + path
        return best, best_path
    else:
        worst = float('inf')
        worst_path = []
        for d in feed_values:
            new_F = update_feed(F, d)
            val, path = minimax_standard(depth-1, True, (R, Q, T, new_F))
            if val < worst:
                worst = val
                worst_path = [state] + path
        return worst, worst_path


# 2. ALPHA-BETA MINIMAX
def minimax_alpha_beta(depth, is_max, state, alpha, beta):
    global eval_count_ab
    R, Q, T, F = state

    if depth == 0:
        eval_count_ab += 1
        purity, energy = simulate(R, Q, T, F)
        return utility(purity, energy), [state]

    if is_max:
        best = float('-inf')
        best_path = []
        prune_flag = False

        for r in reflux_values:
            if prune_flag: break
            for q in heat_values:
                if prune_flag: break
                for t in temp_values:
                    val, path = minimax_alpha_beta(depth-1, False, (r, q, t, F), alpha, beta)
                    if val > best:
                        best = val
                        best_path = [state] + path

                    alpha = max(alpha, best)
                    if beta <= alpha:
                        prune_flag = True
                        break
        return best, best_path
    else:
        worst = float('inf')
        worst_path = []

        for d in feed_values:
            new_F = update_feed(F, d)
            val, path = minimax_alpha_beta(depth-1, True, (R, Q, T, new_F), alpha, beta)
            if val < worst:
                worst = val
                worst_path = [state] + path

            beta = min(beta, worst)
            if beta <= alpha:
                break
        return worst, worst_path


# 3. COMPARISON EXECUTIONER 
initial_state = (2.5, 500, 78, 0.5)
search_depth = 4

print("Running Standard Minimax...")
tracemalloc.start()
start_std = time.time()
val_std, path_std = minimax_standard(search_depth, True, initial_state)
time_std = time.time() - start_std
_, peak_mem_std = tracemalloc.get_traced_memory()
tracemalloc.stop()

print("Running Alpha-Beta Pruning...")
tracemalloc.start()
start_ab = time.time()
val_ab, path_ab = minimax_alpha_beta(search_depth, True, initial_state, float('-inf'), float('inf'))
time_ab = time.time() - start_ab
_, peak_mem_ab = tracemalloc.get_traced_memory()
tracemalloc.stop()

# Derived Metrics 
ebf_std = math.pow(eval_count_std, 1 / search_depth) if eval_count_std > 0 else 0
ebf_ab = math.pow(eval_count_ab, 1 / search_depth) if eval_count_ab > 0 else 0
paths_match = (path_std == path_ab)
nodes_saved = eval_count_std - eval_count_ab

# Output Results
print("\n" + "="*60)
print("                 COMPREHENSIVE PERFORMANCE COMPARISON")
print("="*60)

print(f"\n[1] STANDARD MINIMAX:")
print(f"  - Nodes Evaluated:       {eval_count_std:,}")
print(f"  - Effective Branching:   {ebf_std:.2f} nodes/level")
print(f"  - Peak Memory Usage:     {peak_mem_std / 1024:.2f} KB")
print(f"  - Runtime:               {time_std:.4f} seconds")
print(f"  - Final Utility:         {val_std:.2f}")

print(f"\n[2] ALPHA-BETA PRUNING:")
print(f"  - Nodes Evaluated:       {eval_count_ab:,}")
print(f"  - Effective Branching:   {ebf_ab:.2f} nodes/level")
print(f"  - Peak Memory Usage:     {peak_mem_ab / 1024:.2f} KB")
print(f"  - Runtime:               {time_ab:.4f} seconds")
print(f"  - Final Utility:         {val_ab:.2f}")

print("\n" + "="*60)
print("SUMMARY OF IMPROVEMENTS:")
print(f" * Path Match Verification: {'SUCCESS' if paths_match else '❌ FAILED'}")
print(f" * Nodes Saved:             {nodes_saved:,} ({(nodes_saved / eval_count_std) * 100:.1f}% reduction)")
print(f" * EBF Reduction:           Branching factor reduced by {ebf_std - ebf_ab:.2f}")

if peak_mem_ab < peak_mem_std:
    print(f" * Memory Efficiency:       Saved {(peak_mem_std - peak_mem_ab) / 1024:.2f} KB in call stack")
else:
    print(f" * Memory Overhead:         Used {(peak_mem_ab - peak_mem_std) / 1024:.2f} KB more (expected due to alpha/beta tracking variables)")

print(f" * Speedup Factor:          {time_std / time_ab:.2f}x faster")
print("="*60)

import plotly.graph_objects as go

# 1. Preparing the Data
metrics = ['Total Nodes', 'Execution Time', 'Branching Factor', 'Memory Overhead']

# Protecting against division by zero for extremely fast execution times
t_std_safe = time_std if time_std > 0 else 1e-6

# Calculating raw values (Memory converted to KB)
raw_std = [eval_count_std, t_std_safe, ebf_std, peak_mem_std / 1024]
raw_ab = [eval_count_ab, time_ab, ebf_ab, peak_mem_ab / 1024]

# Calculating percentages (Standard is always 100%)
pct_std = [100, 100, 100, 100]
pct_ab = [(ab / std) * 100 if std > 0 else 0 for ab, std in zip(raw_ab, raw_std)]

# Formatting the text labels that will appear directly on the bars
text_std = [
    f"{eval_count_std:,}",
    f"{t_std_safe:.4f}s",
    f"{ebf_std:.2f}",
    f"{peak_mem_std / 1024:.2f} KB"
]
text_ab = [
    f"{eval_count_ab:,}",
    f"{time_ab:.4f}s",
    f"{ebf_ab:.2f}",
    f"{peak_mem_ab / 1024:.2f} KB"
]

#  2. Building the Single Plotly Graph
fig = go.Figure()

# Adding Standard Minimax Bars (Baseline)
fig.add_trace(go.Bar(
    name='Standard Minimax (Baseline)',
    x=metrics,
    y=pct_std,
    text=text_std,
    textposition='auto',
    marker_color='#EF553B', # Vibrant Coral
    textfont=dict(size=14, color='white', family='Arial Black')
))

# Adding Alpha-Beta Bars
fig.add_trace(go.Bar(
    name='Alpha-Beta Pruning',
    x=metrics,
    y=pct_ab,
    text=text_ab,
    textposition='auto',
    marker_color='#636EFA', # Deep Blue
    textfont=dict(size=14, color='white', family='Arial Black')
))

# 3. Polishing the Layout
fig.update_layout(
    title_text="<b>Algorithm Efficiency Comparison (Normalized to 100%)</b>",
    title_x=0.5,
    title_font_size=22,
    barmode='group',
    template="plotly_white",
    yaxis_title="<b>Percentage of Standard Minimax</b>",
    height=600,
    legend=dict(
        orientation="h",
        yanchor="bottom",
        y=1.02,
        xanchor="right",
        x=1
    ),
    font=dict(family="Arial", size=14, color="#2C3E50")
)

# emphasizing the baseline
fig.add_hline(y=100, line_dash="dash", line_color="gray", annotation_text="Baseline (100%)")

fig.show()

import time
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# 1. Arrays for Data Collection
depths = [2,4,6,8]
nodes_std, nodes_ab = [], []
times_std, times_ab = [], []

initial_state = (2.5, 500, 78, 0.5)

print("Starting Depth Scaling Analysis. Collecting data...")

# 2. Loop
for d in depths:
    print(f"  -> Testing Depth {d}...")

    # Reset counters for this specific depth
    eval_count_std = 0
    eval_count_ab = 0

    # Benchmark Standard Minimax
    t0_std = time.time()
    minimax_standard(d, True, initial_state)
    t1_std = time.time()

    nodes_std.append(eval_count_std)
    times_std.append(t1_std - t0_std)

    # Benchmark Alpha-Beta Pruning
    t0_ab = time.time()
    minimax_alpha_beta(d, True, initial_state, float('-inf'), float('inf'))
    t1_ab = time.time()

    nodes_ab.append(eval_count_ab)
    times_ab.append(t1_ab - t0_ab)

print("Data collection complete! Generating scaling graphs...")

# 3.Plotly Visualizations
fig = make_subplots(
    rows=1, cols=2,
    subplot_titles=('<b>Nodes Evaluated vs. Depth</b>', '<b>Execution Time vs. Depth</b>'),
    horizontal_spacing=0.1
)

# Colors
color_std = '#EF553B' # Coral
color_ab = '#636EFA'  # Blue

# Subplot 1: Nodes vs Depth
fig.add_trace(go.Scatter(x=depths, y=nodes_std, mode='lines+markers', name='Standard Minimax',
                         line=dict(color=color_std, width=3), marker=dict(size=8)), row=1, col=1)
fig.add_trace(go.Scatter(x=depths, y=nodes_ab, mode='lines+markers', name='Alpha-Beta',
                         line=dict(color=color_ab, width=3), marker=dict(size=8)), row=1, col=1)

# Subplot 2: Time vs Depth
fig.add_trace(go.Scatter(x=depths, y=times_std, mode='lines+markers', showlegend=False,
                         line=dict(color=color_std, width=3), marker=dict(size=8)), row=1, col=2)
fig.add_trace(go.Scatter(x=depths, y=times_ab, mode='lines+markers', showlegend=False,
                         line=dict(color=color_ab, width=3), marker=dict(size=8)), row=1, col=2)

# Formatting
fig.update_layout(
    title="<b>Complexity Scaling: Standard Minimax vs. Alpha-Beta</b>",
    title_x=0.5,
    title_font_size=20,
    template="plotly_white",
    height=550,

    # THE FIX: Centered neatly at the bottom
    legend=dict(
        orientation="h",   # Horizontal layout
        yanchor="top",
        y=-0.25,           # Pushed safely below the x-axis titles
        xanchor="center",
        x=0.5              # Centered perfectly
    ),


    margin=dict(t=80, b=120),

    font=dict(family="Arial", size=13)
)

fig.update_xaxes(title_text="Search Depth", tickvals=depths)
fig.update_yaxes(title_text="Number of Nodes", row=1, col=1)
fig.update_yaxes(title_text="Execution Time (Seconds)", row=1, col=2)

fig.show()